[package]
name = "blend"
version = "0.0.1"
authors = ["theo"]
edition = "2021"

exclude = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-schema = "1.1.3"
cosmwasm-std = { version = "1.1.3", features = ["stargate"] }
cw-storage-plus = "1.0.1"
thiserror = { version = "1.0.31" }
mars-owner = "1.2.0"
cw2 = "1.0.1"
